services:
    - type: http
      name: Web Server
      points: 10
      url: http://
      expected_file: expected/index.html

    - type: smtp
      name: Mail Server
      points: 10
      server: 0.0.0.0
      port: 587
      username: test
      password: password

    - type: dns
      name: Internal DNS
      points: 10
      server: 0.0.0.0
      records:
        - name: www.placeholder.com
          type: A
          expected: 0.0.0.0
        - name: mail.placeholder.com
          type: A
          expected: 0.0.0.0

    - type: ftp
      name: FTP Server
      points: 10
      server: 0.0.0.0
      port: 21
      username: user
      password: password
      test_file: test.txt
