services:
    - type: http
      name: HTTP Server
      points: 10
      url: http://0.0.0.0
      expected_file: expected/index.html
      verify_ssl: false

    - type: http
      name: HTTPS Server
      points: 10
      url: https://0.0.0.0
      expected_file: expected/index.html
      verify_ssl: true

    - type: smtp
      name: SMTP Server
      points: 10
      server: 0.0.0.0
      port: 587
      username: test
      password: password

    - type: pop3
      name: POP3 Server
      points: 10
      server: 0.0.0.0
      port: 110
      username: test
      password: password

    - type: dns
      name: DNS
      points: 10
      server: 0.0.0.0
      records:
        - name: www.placeholder.com
          type: A
          expected: 0.0.0.0
        - name: mail.placeholder.com
          type: A
          expected: 0.0.0.0

    - type: ftp
      name: FTP Server
      points: 10
      server: 0.0.0.0
      port: 21
      username: user
      password: password
      test_file: test.txt
